# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  GLFW_config = debug_x64
  ImGui_config = debug_x64
  Glad_config = debug_x64
  yaml_cpp_config = debug_x64
  Box2D_config = debug_x64
  Lua_config = debug_x64
  msdfgen_config = debug_x64
  msdf_atlas_gen_config = debug_x64
  stb_image_config = debug_x64
  lodepng_config = debug_x64
  Base_config = debug_x64
  Basetor_config = debug_x64

else ifeq ($(config),debug_x86)
  GLFW_config = debug_x86
  ImGui_config = debug_x86
  Glad_config = debug_x86
  yaml_cpp_config = debug_x86
  Box2D_config = debug_x86
  Lua_config = debug_x86
  msdfgen_config = debug_x86
  msdf_atlas_gen_config = debug_x86
  stb_image_config = debug_x86
  lodepng_config = debug_x86
  Base_config = debug_x86
  Basetor_config = debug_x86

else ifeq ($(config),release_x64)
  GLFW_config = release_x64
  ImGui_config = release_x64
  Glad_config = release_x64
  yaml_cpp_config = release_x64
  Box2D_config = release_x64
  Lua_config = release_x64
  msdfgen_config = release_x64
  msdf_atlas_gen_config = release_x64
  stb_image_config = release_x64
  lodepng_config = release_x64
  Base_config = release_x64
  Basetor_config = release_x64

else ifeq ($(config),release_x86)
  GLFW_config = release_x86
  ImGui_config = release_x86
  Glad_config = release_x86
  yaml_cpp_config = release_x86
  Box2D_config = release_x86
  Lua_config = release_x86
  msdfgen_config = release_x86
  msdf_atlas_gen_config = release_x86
  stb_image_config = release_x86
  lodepng_config = release_x86
  Base_config = release_x86
  Basetor_config = release_x86

else ifeq ($(config),dist_x64)
  GLFW_config = dist_x64
  ImGui_config = dist_x64
  Glad_config = dist_x64
  yaml_cpp_config = dist_x64
  Box2D_config = dist_x64
  Lua_config = dist_x64
  msdfgen_config = dist_x64
  msdf_atlas_gen_config = dist_x64
  stb_image_config = dist_x64
  lodepng_config = dist_x64
  Base_config = dist_x64
  Basetor_config = dist_x64

else ifeq ($(config),dist_x86)
  GLFW_config = dist_x86
  ImGui_config = dist_x86
  Glad_config = dist_x86
  yaml_cpp_config = dist_x86
  Box2D_config = dist_x86
  Lua_config = dist_x86
  msdfgen_config = dist_x86
  msdf_atlas_gen_config = dist_x86
  stb_image_config = dist_x86
  lodepng_config = dist_x86
  Base_config = dist_x86
  Basetor_config = dist_x86

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW ImGui Glad yaml-cpp Box2D Lua msdfgen msdf-atlas-gen stb_image lodepng Base Basetor

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: Box2D GLFW Glad ImGui Lua lodepng msdf-atlas-gen msdfgen stb_image yaml-cpp

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f GLFW.make config=$(GLFW_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f ImGui.make config=$(ImGui_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f Glad.make config=$(Glad_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f yaml-cpp.make config=$(yaml_cpp_config)
endif

Box2D:
ifneq (,$(Box2D_config))
	@echo "==== Building Box2D ($(Box2D_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f Box2D.make config=$(Box2D_config)
endif

Lua:
ifneq (,$(Lua_config))
	@echo "==== Building Lua ($(Lua_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f Lua.make config=$(Lua_config)
endif

msdfgen:
ifneq (,$(msdfgen_config))
	@echo "==== Building msdfgen ($(msdfgen_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f msdfgen.make config=$(msdfgen_config)
endif

msdf-atlas-gen: msdfgen
ifneq (,$(msdf_atlas_gen_config))
	@echo "==== Building msdf-atlas-gen ($(msdf_atlas_gen_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f msdf-atlas-gen.make config=$(msdf_atlas_gen_config)
endif

stb_image:
ifneq (,$(stb_image_config))
	@echo "==== Building stb_image ($(stb_image_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f stb_image.make config=$(stb_image_config)
endif

lodepng:
ifneq (,$(lodepng_config))
	@echo "==== Building lodepng ($(lodepng_config)) ===="
	@${MAKE} --no-print-directory -C Base/vendor -f lodepng.make config=$(lodepng_config)
endif

Base: Box2D yaml-cpp Glad ImGui GLFW Lua msdfgen msdf-atlas-gen stb_image lodepng
ifneq (,$(Base_config))
	@echo "==== Building Base ($(Base_config)) ===="
	@${MAKE} --no-print-directory -C Base -f Makefile config=$(Base_config)
endif

Basetor: Base Box2D yaml-cpp Glad ImGui GLFW Lua msdfgen msdf-atlas-gen stb_image lodepng
ifneq (,$(Basetor_config))
	@echo "==== Building Basetor ($(Basetor_config)) ===="
	@${MAKE} --no-print-directory -C Basetor -f Makefile config=$(Basetor_config)
endif

clean:
	@${MAKE} --no-print-directory -C Base/vendor -f GLFW.make clean
	@${MAKE} --no-print-directory -C Base/vendor -f ImGui.make clean
	@${MAKE} --no-print-directory -C Base/vendor -f Glad.make clean
	@${MAKE} --no-print-directory -C Base/vendor -f yaml-cpp.make clean
	@${MAKE} --no-print-directory -C Base/vendor -f Box2D.make clean
	@${MAKE} --no-print-directory -C Base/vendor -f Lua.make clean
	@${MAKE} --no-print-directory -C Base/vendor -f msdfgen.make clean
	@${MAKE} --no-print-directory -C Base/vendor -f msdf-atlas-gen.make clean
	@${MAKE} --no-print-directory -C Base/vendor -f stb_image.make clean
	@${MAKE} --no-print-directory -C Base/vendor -f lodepng.make clean
	@${MAKE} --no-print-directory -C Base -f Makefile clean
	@${MAKE} --no-print-directory -C Basetor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  dist_x64"
	@echo "  dist_x86"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   ImGui"
	@echo "   Glad"
	@echo "   yaml-cpp"
	@echo "   Box2D"
	@echo "   Lua"
	@echo "   msdfgen"
	@echo "   msdf-atlas-gen"
	@echo "   stb_image"
	@echo "   lodepng"
	@echo "   Base"
	@echo "   Basetor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"