name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  buildWindows:
    name: build-windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive

    - name: Fetch git submodules
      run: git submodule update --init --recursive

    - name: Running premake5
      run: .\premake5.exe vs2022

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    #- name: Build app for Debug x64
    #  run: msbuild Base.sln -t:rebuild -verbosity:normal -property:Configuration=Debug /p:Platform=x64

    #- name: Build app for Distribution x64
    #  run: msbuild Base.sln -t:rebuild -verbosity:normal -property:Configuration=Dist /p:Platform=x64

    # - name: Zip Release
    #   run: cp Basetor/bin/Dist-windows-x86_64/Basetor/Basetor.exe Basetor/Basetor.exe | 7z a -tzip -r Basetor.zip Basetor/Basetor.exe Basetor/assets Basetor/mono Basetor/Resources Basetor/configurations.lua Basetor/shaders Basetor/imgui.ini Basetor/configurations.lua

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "Windows Dist Build"
        automatic_release_tag: $(git rev-parse --short "${{ github.sha }}")
        prerelease: false
        draft: false
        files: |
          *.zip
